@startuml
cloud internet[
Internet
]

node web[
Web front server
]

package ODA{
node integration[
ESB server
----
Mule
Camel
]

node oda[
ODA application
]
node proxy[
proxy
]
}

node sec1[
Security server
]

package Kapa{
node sec2[
Security server
]

node kapa[
Kapa server
]
}

oda -up-- integration : FHIR/JSON
oda -up--proxy : FHIR/JSON
proxy -up-- web
web -up-- internet
proxy -up-- internet
integration -up--sec1 : CERT
sec1 -up-- sec2 : SOAP/XML
sec2 -up-- kapa

@enduml
